var playing = false;
var score;
var action;
var timeremaining;
var correctAnswer;
var answerList = [
    "Microphone", 
    "Headphone", 
    "Mixer", 
    "Fader", 
    "Knob", 
    "Saxophone", 
    "Keyboard", 
    "Monitor", 
    "Violin", 
    "Top Speaker"
];
var x;
var y;
var correctPosition;
var a, b, c;
var numList = [
1, 2, 3, 4, 5, 6, 7, 8, 9, 10
];

//if we click on the start/reset button
document.getElementById("startreset").onclick = function(){
    //if we are playing
    if(playing == true){
       location.reload(); //reload page
       }else{ //if we are not playing
        
       //change mode to playing
       playing = true;
    
       //set socre to 0
       score = 0; 

document.getElementById("scorevalue").innerHTML = score;
        
           show("timeremaining");
           
        //show countdown box 60 sec
            timeremaining = 60;    

document.getElementById("timeremainingvalue").innerHTML = timeremaining;
     
       //hide game over box
            hide("gameOver");    
           
           
document.getElementById("startreset").innerHTML = "Reset Game";
    //change button to reset
           
    
   //start countdown       
    startCountdown();
           
   //generate Q&A
   generateQA();
        
       } //end of else
} //end of function StartReset

//Clicking on a box
for(q=1; q<5; q++){
    document.getElementById("box"+q).onclick = function(){
    //check if we are playing
    if(playing==true){
            if(this.innerHTML == answerList[y]) //this.innerHTML == correctAnswer
            {
                    //correct Answer
                    //increase socre by 1
                    score++;
                    document.getElementById("scorevalue").innerHTML = score;
                
                    //hide the wrong box
                    hide("wrong");
                    show("correct");
                
                    setTimeout(function(){
                        hide("correct");
                    }, 1500);
                

                generateQA();

                
               }else{
                   //wrong answer
                   hide("correct") 
                   show("wrong");
                
                    setTimeout(function(){
                        hide("wrong");
                    }, 1500);
               }
       }
}
}
//if we click on answer box
    //if we are playing
        //correct?
            //yes
                //increase score
                //show correct box for 1sec
                //generate new Q&A
            //no
                //show try again box for 1sec

//functions

//start counter
function startCountdown(){
    action = setInterval(function(){
        timeremaining -= 1;
    
    document.getElementById("timeremainingvalue").innerHTML = timeremaining;
        
        if(timeremaining == 0){ //game over
            stopCountdown(); 
            //stop the timer
            
           show("gameOver");
    
    document.getElementById("gameOver").innerHTML = "<p>Game Over!</p><p>Your Score is " + score + " .</p>";
    
    document.getElementById("timeremaining").style.display = "none";
            
            hide("timeremaining");
            hide("correct");
            hide("wrong");
            playing = false;
            document.getElementById("startreset").innerHTML = "Start Game";
        }

    },1000);
}


//stop counter
function stopCountdown(){
        clearInterval(action);
}


//hide an element
function hide(Id){
    document.getElementById(Id).style.display = "none";
}

//show an element
function show(Id){
    document.getElementById(Id).style.display = "block";
}
      
//generate QA
function generateQA(){
    

  //original      x = 1 + Math.round(9*Math.random()); //**image id
    
    //new x generated by numList
    for (a = numList.length -1; a > 0; a--){
        b = Math.floor(Math.random() * a)
        c = numList[a]
        numList[a] = numList[b]
        numList[b] = c
    }
    
    x = numList[b]; //get the random number from numList

//    var y = 1 + Math.round(9*Math.random()); 
    y = x-1;
    correctAnswer = y; //**checkthis!!!
    document.getElementById("question").innerHTML = `<img src="img/audio${x}.png">`;
    correctPosition = 1+Math.round(3*Math.random());
    
    document.getElementById("box"+correctPosition).innerHTML = answerList[y]; //fill one box with the correct answer
    
    //fill other boxes with wrong answers
    
    var answers = [correctAnswer];
    var q; //wrongAnswer
    
    for(i=1; i<5; i++){
        if(i != correctPosition) {


            do{
//            wrongAnswer = (1 + Math.round(9*Math.random())*1 + Math.round(9*Math.random()));
            //wrong answer
                q = Math.round(9*Math.random()); //cannot "1 + Math.round(9*Math.random())", because array index start from 0
            }
            while(answers.indexOf(q)>-1)
            document.getElementById("box"+i).innerHTML = answerList[q];
            
            answers.push(q);
        } //end if
    } //end for

} //function generate QA